name: lipreading
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pytorch=1.3.0
  - torchvision=0.4.1
  - cudatoolkit
  - future
  - pytables=3.5.2
  - tqdm=4.36.1
  - editdistance=0.5.3
  - av=6.2.0
  - pip
  - psutil
  - matplotlib=3.1.1
  - pip:
      - opencv-python==4.1.1.26
      - wandb
      - tensorboard==2.0.0
      - git+https://github.com/theSoenke/pytorch-trainer
      # - pillow-simd
      # - imutils==0.5.2
      # - dlib==19.17.0
      # - face_alignment==1.0.0
