name: lipreading
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pytorch=1.3.1
  - torchvision=0.4.2
  - cudatoolkit
  - future
  - pytables=3.5.2
  - tqdm=4.36.1
  - editdistance=0.5.3
  - av=6.2.0
  - pip
  - psutil
  - matplotlib=3.1.1
  - pip:
      - opencv-python==4.1.1.26
      - albumentations==0.4.2
      - scikit-learn==0.21.3
      - wandb
      - wget
      - ray
      - git+https://github.com/theSoenke/pytorch-trainer
      - git+https://github.com/theSoenke/facenet-pytorch.git
      # - dlib==19.18.0
      # - face_alignment==1.0.0
      # - tensorboard==2.0.0
      # - pillow-simd
      # - imutils==0.5.2
