name: lipreading
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.6
  - pytorch=1.2.0
  - torchvision=0.4.0
  - cudatoolkit=10.0
  - future
  - pytables=3.5.2
  - tqdm=4.32.2
  - editdistance=0.5.3
  - av=6.2.0
  - pip
  - pip:
      - tensorboard==1.14.0
      - opencv-python==4.1.0.25
      # - imutils==0.5.2
      # - dlib==19.17.0
      # - face_alignment==1.0.0
      - wandb
      - pillow-simd
      # - pytorch-lightning
      - git+https://github.com/williamFalcon/pytorch-lightning.git
