name: lipreading
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.6
  - pytorch=1.1.0
  - torchvision=0.3.0
  - cudatoolkit=10.0
  - future
  - imageio=2.5.0
  - imageio-ffmpeg=0.3.0
  - pytables=3.5.2
  - tqdm=4.32.2
  - pip
  - pip:
      - tensorboard==1.14.0
